---
name: Build

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Node.js
        id: setup_node
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
        with:
          node-version: lts/hydrogen

      - name: Install dependencies
        id: install_dependencies
        run: npm install

      - name: Build
        id: build
        run: npx eleventy
